baseURL = "https://www.peterbaumgartner.com/"
title = "Peter Baumgartner"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "PaperMod"

disqusShortname = ""
googleAnalytics = "UA-72692144-1"

Paginate = 15
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.profileMode]
enabled = true
title = "Peter Baumgartner"
subtitle = "Data Scientist & NLP Engineer"
imageUrl = "https://i.ibb.co/LYz2DyQ/1537215809678.jpg"
imageTitle = "Peter Baumgartner"
imageWidth = 120
imageHeight = 120

[[params.profileMode.buttons]]
name = "blog"
url = "/blog"

[[params.socialIcons]]
name = "twitter"
url = "https://www.twitter.com/pmbaumgartner"

[[params.socialIcons]]
name = "Github"
url = "https://github.com/"

[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/peterbaumgartner/"

[params.info]
description = ""
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006-01-02"
listDateFormat = "2006-01-02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideSocialMenu = true
showReadingTime = true
taxonomyCloudShuffle = true
accentColor = "#297FD5"

[params.sidebar]
enable = true

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "petermbaumgartner@gmail.com"
github = "pmbaumgartner"
twitter = "pmbaumgartner"

[params.comments]
enable = false

[params.comments.staticman]
enable = false
apiEndpoint = "https://api.staticman.net/v2/entry"
maxDepth = 2

[params.comments.staticman.github]
username = ""
repository = ""
branch = "master"

[permalinks]
page = "/:slug/"

[blackfriday]
hrefTargetBlank = false

[markup.goldmark.renderer]
unsafe = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
