baseURL = "https://neriman.me/"
title = "Nəriman Məmmədli"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = "CC-BY-SA 4.0"

theme = "PaperMod"

enableRobotsTXT = true # generate robots.txt

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.profileMode]
enabled = true
title = "Nəriman Məmmədli"
subtitle = "A random person"
imageUrl = "images/profile.jpg"
imageTitle = "Nəriman Məmmədli"
imageWidth = 120
imageHeight = 120

# [[params.profileMode.buttons]]
# name = "about"
# url = "/about"

[[params.socialIcons]]
name = "twitter"
url = "https://www.twitter.com/nerim4n"

[[params.socialIcons]]
name = "Github"
url = "https://github.com/nemoralis/"

[[params.socialIcons]]
name = "Instagram"
url = "https://instagram.com/nerim4nm"

[params.info]
description = ""
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.png"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = ""                    # used in 404 template ( Generator: https://gopherize.me )

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006-01-02"
listDateFormat = "2006-01-02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideSocialMenu = true
showReadingTime = true
taxonomyCloudShuffle = true
accentColor = "#297FD5"

[params.sidebar]
enable = true

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "contact@neriman.me"
github = "nemoralis"
twitter = "nerim4n"

[params.comments]
enable = false

[params.comments.staticman]
enable = false
apiEndpoint = "https://api.staticman.net/v2/entry"
maxDepth = 2

[params.comments.staticman.github]
username = ""
repository = ""
branch = "master"

[permalinks]
page = "/:slug/"

[blackfriday]
hrefTargetBlank = false

[markup.goldmark.renderer]
unsafe = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
